apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tanguylichau/backendapp:5.0
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
