apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        # Use the non-privileged PSP
        podSecurityPolicyName: non-privileged_psp
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP