apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: database
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - '*'
  volumes:
    - '*'
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'MustRunAs'
    ranges:
      - min: 26
        max: 26
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 26
        max: 26
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 26
        max: 26